### ISSUE TITLE
The setting of simulation card

### ISSUE THREAD

**Issue by daxiang415** [samuelduchesne/trnsystor#43]
Dear author, 

Thanks a lot for your code and work. I may have a very naive problem since I am just starting the learning of trnsys. 

Could we just modify the simulation card so that when we recall the py file for one time, the simulation will process only one step further?

**Comment by samuelduchesne** [comment]
I am not sure I understand the question. What are you trying to achieve?

**Comment by daxiang415** [comment]
Sorry for the confusion, here is the thing. Currently, I am trying to use the trnsys model and reinforcement learning to deal with the problem of operational optimization. I need to first get the control policy from a python file, input the policy to the trnsys model, and run simulation for one time step, get the simulation results for the response of RL to do future decision. So I just need the simulation card working in that kind of style, is there any option to achieve my goal?

**Comment by samuelduchesne** [comment]
I see. What I think you are trying to achieve is something called a co-simulator, where TRNSYS releases component values to an external program, waits for the external program to return a value and then continues to the next time-step. To learn more, look for Functional Mockup Interface (https://www.iea-annex60.org/finalReport/activity_1_2.html).

I will close this now.
